#!/bin/bash

OUT="Android.sources.bp"

REQUIRED_MODULE_NAMES=()

cat << EOF > ${OUT}
// Autogenerated by gen_bp.sh, do not touch

filegroup {
    name: "nano_sources",
    srcs: [
EOF

for src in $(ls src/*.c); do
    echo "        \"${src}\"," >> ${OUT}
done

cat << EOF >> ${OUT}
    ],
}

EOF

for nanorc in $(ls -1 syntax/*.nanorc | tr '\n' '\0' | xargs -0 -n 1 basename); do
    REQUIRED_MODULE_NAMES+=("${nanorc}")
    echo "prebuilt_etc {
    name: \"${nanorc}\",
    src: \"syntax/${nanorc}\",
    filename_from_src: true,
    relative_install_path: \"nano\",
    system_ext_specific: true,
}
" >> ${OUT}
done

cat << EOF >> ${OUT}
cc_defaults {
    name: "nano_etc_files",
    required: [
EOF

for module in "${REQUIRED_MODULE_NAMES[@]}"; do
    echo "        \"${module}\"," >> ${OUT}
done

cat << EOF >> ${OUT}
    ],
}
EOF
